"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-26 13:39:49.050773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_name', sa.String(length=60), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('route', sa.String(length=120), nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('properties_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_created_at'), 'analytics_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_name'), 'analytics_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_analytics_events_owner_id'), 'analytics_events', ['owner_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('actor_account', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=120), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('entitlements',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('total_paths', sa.Integer(), nullable=False),
    sa.Column('used_paths', sa.Integer(), nullable=False),
    sa.Column('installed', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('installed_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('skill_key', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('api_key_ready', sa.Boolean(), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False),
    sa.Column('installed_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installed_skills_owner_id'), 'installed_skills', ['owner_id'], unique=False)
    op.create_table('login_throttles',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('account', sa.String(length=255), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('window_started_at', sa.Float(), nullable=False),
    sa.Column('locked_until', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_login_throttles_account'), 'login_throttles', ['account'], unique=False)
    op.create_table('model_services',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('vendor', sa.String(length=80), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('protocol', sa.String(length=30), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False),
    sa.Column('api_key_ready', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'owner_id')
    )
    op.create_table('payment_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('provider_event_id', sa.String(length=180), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('received_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_events_order_id'), 'payment_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_events_provider_event_id'), 'payment_events', ['provider_event_id'], unique=False)
    op.create_index(op.f('ix_payment_events_received_at'), 'payment_events', ['received_at'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('path_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_owner_id'), 'sessions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_sessions_project_id'), 'sessions', ['project_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('identity', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('password_salt', sa.String(length=64), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('disabled_at', sa.Float(), nullable=True),
    sa.Column('disabled_reason', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_identity'), 'users', ['identity'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_session_id'), 'files', ['session_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('meta_json', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_owner_id'), 'messages', ['owner_id'], unique=False)
    op.create_index(op.f('ix_messages_project_id'), 'messages', ['project_id'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table('model_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('service_owner_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=60), nullable=False),
    sa.Column('model_id', sa.String(length=160), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('context_tokens', sa.Integer(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['service_owner_id', 'service_id'], ['model_services.owner_id', 'model_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'service_owner_id', 'service_id'),
    sa.UniqueConstraint('service_owner_id', 'service_id', 'model_id', name='uq_model_entries_owner_route_model')
    )
    op.create_table('mvp_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('installed_skill_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('vertical', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_step_order', sa.Integer(), nullable=False),
    sa.Column('blocker', sa.Text(), nullable=False),
    sa.Column('next_action', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['installed_skill_id'], ['installed_skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mvp_runs_owner_id'), 'mvp_runs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_mvp_runs_status'), 'mvp_runs', ['status'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('path_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_order_id', sa.String(length=120), nullable=False),
    sa.Column('payment_url', sa.String(length=1000), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=180), nullable=False),
    sa.Column('paid_at', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_owner_id'), 'orders', ['owner_id'], unique=False)
    op.create_index(op.f('ix_orders_provider_order_id'), 'orders', ['provider_order_id'], unique=False)
    op.create_index(op.f('ix_orders_provider_transaction_id'), 'orders', ['provider_transaction_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('thread_states',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('selected_text', sa.Text(), nullable=False),
    sa.Column('source_message_id', sa.String(length=100), nullable=False),
    sa.Column('source_message_role', sa.String(length=20), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('is_minimized', sa.Boolean(), nullable=False),
    sa.Column('z_index', sa.Integer(), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thread_states_session_id'), 'thread_states', ['session_id'], unique=False)
    op.create_table('threads',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('parent_thread_id', sa.String(length=100), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('last_activity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_parent_thread_id'), 'threads', ['parent_thread_id'], unique=False)
    op.create_index(op.f('ix_threads_session_id'), 'threads', ['session_id'], unique=False)
    op.create_table('harness_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('mvp_run_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['mvp_run_id'], ['mvp_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harness_projects_mvp_run_id'), 'harness_projects', ['mvp_run_id'], unique=False)
    op.create_index(op.f('ix_harness_projects_owner_id'), 'harness_projects', ['owner_id'], unique=False)
    op.create_table('run_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_key', sa.String(length=50), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('objective', sa.String(length=300), nullable=False),
    sa.Column('required_artifact', sa.String(length=120), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['mvp_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_steps_run_id'), 'run_steps', ['run_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('mvp_run_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=False),
    sa.Column('started_at', sa.Float(), nullable=True),
    sa.Column('finished_at', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['harness_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_mvp_run_id'), 'agent_runs', ['mvp_run_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_owner_id'), 'agent_runs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_project_id'), 'agent_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_session_id'), 'agent_runs', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('harness_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['harness_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harness_documents_owner_id'), 'harness_documents', ['owner_id'], unique=False)
    op.create_index(op.f('ix_harness_documents_project_id'), 'harness_documents', ['project_id'], unique=False)
    op.create_table('harness_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['harness_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harness_files_owner_id'), 'harness_files', ['owner_id'], unique=False)
    op.create_index(op.f('ix_harness_files_project_id'), 'harness_files', ['project_id'], unique=False)
    op.create_table('harness_memories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('memory_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['harness_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harness_memories_owner_id'), 'harness_memories', ['owner_id'], unique=False)
    op.create_index(op.f('ix_harness_memories_project_id'), 'harness_memories', ['project_id'], unique=False)
    op.create_table('run_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['mvp_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['run_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_artifacts_run_id'), 'run_artifacts', ['run_id'], unique=False)
    op.create_index(op.f('ix_run_artifacts_step_id'), 'run_artifacts', ['step_id'], unique=False)
    op.create_table('run_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['mvp_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['run_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_events_run_id'), 'run_events', ['run_id'], unique=False)
    op.create_table('agent_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_events_agent_run_id'), 'agent_events', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_events_created_at'), 'agent_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_events_event_type'), 'agent_events', ['event_type'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('arguments_json', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('started_at', sa.Float(), nullable=True),
    sa.Column('ended_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_agent_run_id'), 'tool_calls', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_name'), 'tool_calls', ['name'], unique=False)
    op.create_index(op.f('ix_tool_calls_owner_id'), 'tool_calls', ['owner_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_status'), 'tool_calls', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_calls_status'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_owner_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_name'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_agent_run_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_agent_events_event_type'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_created_at'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_agent_run_id'), table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index(op.f('ix_run_events_run_id'), table_name='run_events')
    op.drop_table('run_events')
    op.drop_index(op.f('ix_run_artifacts_step_id'), table_name='run_artifacts')
    op.drop_index(op.f('ix_run_artifacts_run_id'), table_name='run_artifacts')
    op.drop_table('run_artifacts')
    op.drop_index(op.f('ix_harness_memories_project_id'), table_name='harness_memories')
    op.drop_index(op.f('ix_harness_memories_owner_id'), table_name='harness_memories')
    op.drop_table('harness_memories')
    op.drop_index(op.f('ix_harness_files_project_id'), table_name='harness_files')
    op.drop_index(op.f('ix_harness_files_owner_id'), table_name='harness_files')
    op.drop_table('harness_files')
    op.drop_index(op.f('ix_harness_documents_project_id'), table_name='harness_documents')
    op.drop_index(op.f('ix_harness_documents_owner_id'), table_name='harness_documents')
    op.drop_table('harness_documents')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_session_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_project_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_owner_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_mvp_run_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_run_steps_run_id'), table_name='run_steps')
    op.drop_table('run_steps')
    op.drop_index(op.f('ix_harness_projects_owner_id'), table_name='harness_projects')
    op.drop_index(op.f('ix_harness_projects_mvp_run_id'), table_name='harness_projects')
    op.drop_table('harness_projects')
    op.drop_index(op.f('ix_threads_session_id'), table_name='threads')
    op.drop_index(op.f('ix_threads_parent_thread_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_thread_states_session_id'), table_name='thread_states')
    op.drop_table('thread_states')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_provider_transaction_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_provider_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_owner_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_mvp_runs_status'), table_name='mvp_runs')
    op.drop_index(op.f('ix_mvp_runs_owner_id'), table_name='mvp_runs')
    op.drop_table('mvp_runs')
    op.drop_table('model_entries')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_project_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_owner_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_files_session_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_users_identity'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sessions_project_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_owner_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('products')
    op.drop_index(op.f('ix_payment_events_received_at'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_provider_event_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_order_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_table('model_services')
    op.drop_index(op.f('ix_login_throttles_account'), table_name='login_throttles')
    op.drop_table('login_throttles')
    op.drop_index(op.f('ix_installed_skills_owner_id'), table_name='installed_skills')
    op.drop_table('installed_skills')
    op.drop_table('entitlements')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_analytics_events_owner_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_name'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_created_at'), table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
